# hcloud cax guests are KVM on Ampere Altra: UEFI with ACPI, PSCI, GICv3,
# virtio-scsi and virtio-net on PCIe. The VNC console shows the EFI
# framebuffer; the serial ports are a PCI 16550 (hcloud) and the PL011 of
# QEMU virt (the boot test).
{
  enable = [
    "ACPI"
    "ACPI_BUTTON"
    "ARM_PSCI_FW"
    # kexec parks the secondary CPUs through CPU hotplug, which arm64 only
    # offers with PM_SLEEP_SMP
    "SUSPEND"
    "HOTPLUG_CPU"
    "ARM_SMCCC_SOC_ID"
    "PCI_HOST_GENERIC"
    "DMI"
    "DMIID"
    "DMI_SYSFS"
    "FW_CFG_SYSFS"
    "RTC_CLASS"
    "RTC_DRV_EFI"
    "RTC_DRV_PL031"
    "VIRTIO"
    "VIRTIO_MENU"
    "VIRTIO_PCI"
    "VIRTIO_MMIO"
    "VIRTIO_BALLOON"
    "VIRTIO_CONSOLE"
    "VIRTIO_BLK"
    "VIRTIO_NET"
    "SCSI"
    "SCSI_LOWLEVEL"
    "SCSI_VIRTIO"
    "BLK_DEV_SD"
    "HW_RANDOM"
    "HW_RANDOM_VIRTIO"
    "HW_RANDOM_ARM_SMCCC_TRNG"
    "NET_9P"
    "NET_9P_VIRTIO"
    "9P_FS"
    "9P_FS_POSIX_ACL"
    "VIRTIO_FS"
    "VT"
    "VT_CONSOLE"
    "FB"
    "FB_EFI"
    "FRAMEBUFFER_CONSOLE"
    "SERIAL_8250"
    "SERIAL_8250_CONSOLE"
    "SERIAL_8250_PCI"
    "SERIAL_AMBA_PL011"
    "SERIAL_AMBA_PL011_CONSOLE"
  ];
  disable = [
    # virtio-gpu would take the console from efifb and needs DRM
    "DRM"
    # efifb binds efi-framebuffer; SYSFB_SIMPLEFB would turn it into
    # simple-framebuffer and leave the UEFI console without a driver
    "SYSFB_SIMPLEFB"
    # SoC platforms that virt.config does not turn off
    "ARCH_AIROHA"
    "ARCH_ARTPEC"
    "ARCH_AXIADO"
    "ARCH_BLAIZE"
    "ARCH_CIX"
    "ARCH_SOPHGO"
    "ATA"
    "ETHERNET"
    "PHYLIB"
    "WATCHDOG"
    "HWMON"
    "CPU_FREQ"
    "XEN"
    "HYPERV"
    "NUMA"
    "I2C"
    "GPIOLIB"
    "IOMMU_SUPPORT"
    "ARM_SMMU_V3"
    "PINCTRL"
    "COMMON_CLK"
    "REMOTEPROC"
    "RPMSG"
    "SOUNDWIRE"
    "MMC"
    "MAILBOX"
    "PHY"
    "NVMEM"
    "INTERCONNECT"
    "ARM_SCMI_PROTOCOL"
  ];
}
